[project]
name = "ydits-twitter"
version = "2.4.0"
description = "防災情報を提供する X Bot"
readme = "README.md"
authors = [
    { name = "よね/Yone", email = "pypi@yoneyo.com" }
]
requires-python = ">=3.14"
dependencies = [
    "requests-oauthlib>=2.0.0",
]

[project.scripts]
ydits-twitter = "ydits_twitter.__main__:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
